import nextCoreWebVitals from 'eslint-config-next/core-web-vitals';
import nextTypescript from 'eslint-config-next/typescript';
import prettierRecommended from 'eslint-plugin-prettier/recommended';
import unusedImports from 'eslint-plugin-unused-imports';

// ESLint 9 flat config. Replaces the old `.eslintrc` (airbnb + next + prettier)
// after Next 16 removed `next lint`. We keep Next's core-web-vitals + TypeScript
// rules, import ordering, unused-import detection and Prettier formatting, and
// drop airbnb (no first-class flat-config support; its rules are largely
// Prettier's job). Run with `npm run lint`.
const config = [
  {
    ignores: [
      'node_modules/**',
      'out/**',
      '.next/**',
      'next-env.d.ts', // auto-generated by Next; not ours to lint
    ],
  },

  ...nextCoreWebVitals,
  ...nextTypescript,

  // Root config files (next.config.js, tailwind.config.js, postcss.config.js,
  // lint-staged.config.js) are CommonJS — `require`/`module.exports` are fine.
  {
    files: ['*.js'],
    languageOptions: { sourceType: 'commonjs' },
    rules: {
      '@typescript-eslint/no-require-imports': 'off',
    },
  },

  {
    files: ['**/*.{js,jsx,ts,tsx,mjs,cjs}'],
    plugins: { 'unused-imports': unusedImports },
    rules: {
      // Vscode doesn't support automatically destructuring, it's a pain to add a new variable
      'react/destructuring-assignment': 'off',
      // Next.js uses its own internal link system
      'jsx-a11y/anchor-is-valid': 'off',
      // Allow non-defined react props as undefined
      'react/require-default-props': 'off',
      // _app.tsx uses the spread operator and also react-hook-form
      'react/jsx-props-no-spreading': 'off',
      // We are currently not using next/image because it isn't supported with SSG mode
      '@next/next/no-img-element': 'off',
      // Named export is easier to refactor automatically
      'import/prefer-default-export': 'off',
      // _document.tsx uses a render method without `this`
      'class-methods-use-this': 'off',
      'import/order': [
        'error',
        {
          groups: ['builtin', 'external', 'internal'],
          pathGroups: [
            { pattern: 'react', group: 'external', position: 'before' },
          ],
          pathGroupsExcludedImportTypes: ['react'],
          'newlines-between': 'always',
          alphabetize: { order: 'asc', caseInsensitive: true },
        },
      ],
      // unused-imports supersedes the core/TS no-unused-vars rules
      '@typescript-eslint/no-unused-vars': 'off',
      'unused-imports/no-unused-imports': 'error',
      'unused-imports/no-unused-vars': ['error', { argsIgnorePattern: '^_' }],
    },
  },

  // Must come after the configs above so it can turn off conflicting
  // formatting rules; the trailing override pins Prettier options.
  prettierRecommended,
  {
    files: ['**/*.{js,jsx,ts,tsx,mjs,cjs}'],
    rules: {
      'prettier/prettier': [
        'error',
        // trailingComma:'es5' preserves the Prettier-2 formatting the repo was
        // written with, so upgrading to Prettier 3 doesn't reformat everything.
        { singleQuote: true, trailingComma: 'es5' },
      ],
    },
  },
];

export default config;
